# Generated by Django 5.0.2 on 2026-03-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата заказа', 'verbose_name_plural': 'Оплаты заказов'},
        ),
    ]
