# Generated by Django 5.0.2 on 2026-02-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='Введите название бренда', max_length=150, unique=True, verbose_name='Название бренда'),
        ),
    ]
