# Generated by Django 5.0.2 on 2025-10-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Товар в наличии')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='Картинка товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(related_name='products', to='category.category', verbose_name='Категории товара')),
            ],
        ),
    ]
