# Generated by Django 5.0.2 on 2026-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('product', 'О товаре'), ('store', 'О магазине'), ('delivery', 'О доставке')], default='store', max_length=20),
        ),
    ]
