# Generated by Django 5.0.2 on 2026-04-03 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0004_productvariation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.productvariation'),
        ),

        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'variation')},
        ),
    ]
