# Generated by Django 5.0.2 on 2026-03-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profileuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
