# Generated by Django 5.0.2 on 2025-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('crypto', 'Крипта')], default='card', max_length=25),
        ),
    ]
