# Generated by Django 5.0.2 on 2026-03-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_price_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
